name: Trigger Central Pipeline
on:
  push:
    branches:
      - 'feature/*'
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Central Pipeline
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/bathas2021/api-deploy/dispatches \
          -d '{"event_type": "api-updated-nprod", "client_payload": {
          "api_name": "bathas2021/demo-api-2",
          "branch_name": "${{ github.ref_name }}",
          "repo_name": "${{ github.repository }}"
          }}'
